# Generated by Django 5.2.3 on 2025-07-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_mgnt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='installed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='request_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='bin_type',
            field=models.CharField(choices=[('general', 'General Waste'), ('recycling', 'Recycling'), ('organic', 'Organic Waste')], default='General Waste', max_length=20),
        ),
    ]
